### ISSUE TITLE
problem with de_DE to de

### ISSUE THREAD

**Issue by microelly2** [agermanidis/autosub#3] opened 2015-07-09 20:11 UTC
Traceback (most recent call last):
  File "/usr/local/bin/autosub", line 257, in <module>
    sys.exit(main())
  File "/usr/local/bin/autosub", line 240, in main
    formatted_subtitles = formatter(timed_subtitles)
  File "/usr/local/lib/python2.7/dist-packages/autosub/formatters.py", line 13, in srt_formatter
    return '\n'.join(map(str, f))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 34: ordinal not in range(128)

Would be nice to catch these exceptions to get the rest running.

**Comment by agermanidis** [comment] 2015-07-09 20:34
Pushed a possible fix. Can't reproduce the problem right now so I'm not sure this will work. If it doesn't can you send me the input file that you're using? Thanks.

**Comment by agermanidis** [comment] 2015-08-07 17:27
should be fixed by https://github.com/agermanidis/autosub/pull/8

**Closed by agermanidis** 2015-08-07 17:27 UTC
